name: Go CI

on:
  pull_request:
    branches: [ main, next, feature/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
      - name: go information
        run: |
          go version && go env
      - name: add gopath
        run: |
          export GOPATH=$(go env GOPATH)
          export PATH="$GOPATH/bin:$PATH"
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.6.2
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Format
        run: make fmt
      - name: Lint
        run: make lint